# Generated by Django 5.2.5 on 2026-08-30 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cote', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('gagne', 'Gagné'), ('perdu', 'Perdu'), ('rembourse', 'Remboursé')], default='en_cours', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SignalFraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_anomalie', models.CharField(choices=[('collusion', 'Collusion'), ('autopari', 'Auto-pari'), ('temps_reponse', 'Temps de réponse anormal'), ('martelage', 'Martelage (rate limited)')], max_length=30)),
                ('score_suspicion', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
