# Generated by Django 5.2.5 on 2026-08-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenue', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publicites/')),
                ('lien', models.URLField(blank=True, default='')),
                ('actif', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='SignalementContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('objet_id', models.PositiveIntegerField()),
                ('motif', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('a_traiter', 'À traiter'), ('modere', 'Modéré'), ('rejete', 'Rejeté')], default='a_traiter', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
