# Generated by Django 5.2.17 on 2026-09-05 20:42

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', apps.users.models.UtilisateurManager()),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
