# Generated by Django 5.2.5 on 2026-09-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_messageami'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageami',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
