# Generated by Django 5.2.17 on 2026-09-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_add_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='category',
            field=models.CharField(default='Quizz', max_length=50),
        ),
    ]
