# Generated by Django 5.2.5 on 2026-08-30 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_recharge', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('solde_gains', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('mise_bloquee', 'Mise bloquée'), ('gain', 'Gain'), ('commission', 'Commission plateforme'), ('remboursement', 'Remboursement'), ('perte', 'Perte pari')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('solde_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('succes', 'Succès'), ('echoue', 'Échoué')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallet.portefeuille')),
            ],
            options={
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='uniq_ledger_idem')],
            },
        ),
    ]
