# Generated by Django 5.2.17 on 2026-09-06 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'verbose_name': 'Capital plateforme',
                'verbose_name_plural': 'Capital plateforme',
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='bloque_apres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='bloque_avant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reference_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reference_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='solde_avant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='derniere_recharge_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='pin_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='solde_bloque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='portefeuille',
            name='unlocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('demo_credit_initial', 'Crédit initial DEMO'), ('demo_recharge', 'Recharge DEMO'), ('mise_bloquee', 'Mise réservée'), ('mise_engagee', 'Mise engagée'), ('mise_liberee', 'Mise libérée'), ('gain', 'Gain'), ('commission', 'Commission plateforme'), ('remboursement', 'Remboursement'), ('perte', 'Perte pari'), ('transfert', 'Transfert DEMO')], max_length=25),
        ),
        migrations.CreateModel(
            name='PlatformeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('commission', 'Commission plateforme'), ('ajustement', 'Ajustement compensatoire')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('capital_avant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('capital_apres', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('game_id', models.CharField(blank=True, default='', max_length=100)),
                ('bet_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('platforme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.platformewallet')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PortefeuilleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pin_failed', 'PIN incorrect'), ('wallet_unlocked', 'Portefeuille déverrouillé'), ('wallet_locked', 'Portefeuille verrouillé'), ('pin_set', 'PIN défini'), ('pin_changed', 'PIN modifié')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='wallet.portefeuille')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
