# Generated by Django 5.2.17 on 2026-09-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_platformewallet_ledgerentry_bloque_apres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefeuilleevent',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
