# Generated by Django 5.2.17 on 2026-09-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_global', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizglobalgamequestion',
            new_name='quiz_global_game_id_3101f0_idx',
            old_name='quiz_global_game_id_turn_idx',
        ),
        migrations.RenameIndex(
            model_name='quizglobalgamequestion',
            new_name='quiz_global_game_id_51f424_idx',
            old_name='quiz_global_game_id_q_idx',
        ),
        migrations.RenameIndex(
            model_name='quizglobalgamequestion',
            new_name='quiz_global_game_id_b0a10e_idx',
            old_name='quiz_global_game_id_th_idx',
        ),
        migrations.RenameIndex(
            model_name='quizglobalplayeranswer',
            new_name='quiz_global_game_qu_01edab_idx',
            old_name='quiz_global_gq_player_idx',
        ),
    ]
