# Generated by Django 5.2.17 on 2026-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_global', '0002_rename_quiz_global_game_id_turn_idx_quiz_global_game_id_3101f0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizglobalgame',
            name='mise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='quizglobalgame',
            name='mise_proposee_invite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
