# Generated by Django 5.2.17 on 2026-09-09 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remape_statuts_tie_break(apps, schema_editor):
    """Remplace l'ancienne valeur de statut TIE_BREAK par TIE_BREAK_THEME."""
    QuizGlobalGame = apps.get_model("quiz_global", "QuizGlobalGame")
    QuizGlobalGame.objects.filter(status="TIE_BREAK").update(status="TIE_BREAK_THEME")


def remape_inverse(apps, schema_editor):
    QuizGlobalGame = apps.get_model("quiz_global", "QuizGlobalGame")
    QuizGlobalGame.objects.filter(status="TIE_BREAK_THEME").update(status="TIE_BREAK")


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_global', '0003_quizglobalgame_mise_and_more'),
        ('users', '0003_alter_utilisateur_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remape_statuts_tie_break, remape_inverse),
        migrations.AddField(
            model_name='quizglobalgame',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobalgame',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizglobalgame',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('THEME_SELECTION', 'Theme Selection'), ('QUESTION_READING', 'Question Reading'), ('ANSWERING', 'Answering'), ('QUESTION_FINISHED', 'Question Finished'), ('TIE_BREAK_THEME', 'Tie Break Theme'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('ABANDONED', 'Abandoned')], default='WAITING', max_length=40),
        ),
        migrations.CreateModel(
            name='QuizGlobalActivePlayer',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quiz_global_active', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_players', to='quiz_global.quizglobalgame')),
            ],
        ),
        migrations.CreateModel(
            name='QuizGlobalInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='quiz_global.quizglobalgame')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_global_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_global_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['receiver', 'status'], name='quiz_global_receive_72b972_idx'), models.Index(fields=['game', 'status'], name='quiz_global_game_id_a562c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'receiver'), name='quiz_global_unique_invitee')],
            },
        ),
    ]
