# Generated by Django 5.2.17 on 2026-09-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_global', '0007_converge_prod_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizglobalgame',
            name='abandoned_at',
        ),
        migrations.RemoveField(
            model_name='quizglobalgame',
            name='expired_at',
        ),
    ]
