# Generated by Django 5.2.17 on 2026-09-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_global', '0008_remove_quizglobalgame_abandoned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizglobalgame',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobalgame',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
