# Generated by Django 5.2.17 on 2026-09-06 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_publication_lien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('defi_recu', 'Défi reçu'), ('defi_accepte', 'Défi accepté'), ('ami_accepte', 'Demande acceptée'), ('systeme', 'Système')], default='systeme', max_length=30),
        ),
    ]
