# Generated by Django 5.2.5 on 2026-08-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_jeu', models.CharField(choices=[('classique', 'Classique'), ('intrus', "L'intrus")], default='classique', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', "En attente d'adversaire"), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('mise', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('score_cible', models.PositiveIntegerField(default=8)),
                ('score_hote', models.PositiveIntegerField(default=0)),
                ('score_invite', models.PositiveIntegerField(default=0)),
                ('tour_actuel', models.PositiveIntegerField(default=0)),
                ('commence_le', models.DateTimeField(blank=True, null=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('score_final', models.PositiveIntegerField(default=0)),
                ('vainqueur', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReponseTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('correcte', models.BooleanField(default=False)),
                ('duree_ms', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
