# Generated by Django 5.2.5 on 2026-08-30 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='joueur_hote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchs_hotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='joueur_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchs_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchs', to='themes.theme'),
        ),
        migrations.AddField(
            model_name='match',
            name='vainqueur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_gagnes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='matches.match'),
        ),
        migrations.AddField(
            model_name='participation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reponsetour',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='themes.reponse'),
        ),
        migrations.AddField(
            model_name='reponsetour',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='matches.match'),
        ),
        migrations.AddField(
            model_name='tour',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='themes.question'),
        ),
        migrations.AddField(
            model_name='reponsetour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='matches.tour'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('match', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='tour',
            unique_together={('match', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='reponsetour',
            unique_together={('tour', 'utilisateur')},
        ),
    ]
