# Generated by Django 5.2.17 on 2026-09-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mise_proposee_invite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='type_jeu',
            field=models.CharField(choices=[('classique', 'Classique'), ('intrus', "L'intrus"), ('course_lapin', 'Course lapin')], default='classique', max_length=20),
        ),
    ]
